        "CREATE TABLE IF NOT EXISTS tab2 ("
            "col1 INTEGER PRIMARY KEY AUTOINCREMENT, "
            "col2 INTEGER REFERENCES tab1(col1), "
            "col3 TEXT NOT NULL, "
            "col4 REAL NOT NULL, "
            "col5 INTEGER NOT NULL, "
            "col6 TEXT, "
            "col7 REAL, "
            "col8 INTEGER"
        ");"
